# Generated by Django 2.2.5 on 2019-10-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intro',
        ),
    ]
